### ISSUE TITLE
Support ensure => absent for defined types

### ISSUE THREAD

**Issue by mkrakowitzer** [razorsedge/puppet-network#79]
I am unable to ensure a defined type is absent, only up or down.
 
```yaml
network_aliases:
  'eth0:2':
    ensure:    'absent'
```

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must pass ipaddress to Network::Alias[eth0:8] on node fhl-r1papppp01.fnb.co.za
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

network::alias::range appears as if it might support this, other defined types should too.
